# Generated by Django 3.0.7 on 2020-07-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('rank', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'game_users',
            },
        ),
        migrations.CreateModel(
            name='SpeedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'speed_types',
            },
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'team_types',
            },
        ),
        migrations.CreateModel(
            name='UserTrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumul_dist', models.TextField()),
                ('game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.GameUser')),
                ('team_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.TeamType')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Track')),
            ],
            options={
                'db_table': 'user_track_records',
            },
        ),
        migrations.CreateModel(
            name='UserTrackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_cnt', models.IntegerField()),
                ('win_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('best_lap', models.CharField(max_length=50)),
                ('game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.GameUser')),
                ('team_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.TeamType')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Track')),
            ],
            options={
                'db_table': 'user_track_info',
            },
        ),
        migrations.CreateModel(
            name='UserPageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('game_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rank.GameUser')),
            ],
            options={
                'db_table': 'user_page_hits',
            },
        ),
        migrations.CreateModel(
            name='UserKart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_cnt', models.IntegerField()),
                ('win_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retire_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('track_history', models.TextField()),
                ('game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.GameUser')),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Kart')),
                ('team_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.TeamType')),
            ],
            options={
                'db_table': 'user_kart',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('rank_diff', models.IntegerField(null=True)),
                ('cumul_point', models.IntegerField()),
                ('point_get', models.IntegerField()),
                ('win_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retire_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('play_cnt', models.IntegerField()),
                ('avg_rank', models.IntegerField(null=True)),
                ('game_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rank.GameUser')),
                ('team_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.TeamType')),
            ],
            options={
                'db_table': 'rankings',
            },
        ),
        migrations.AddField(
            model_name='gameuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rank.TeamType'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_cnt', models.IntegerField()),
                ('win_cnt', models.IntegerField()),
                ('retire_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank_avg_50', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank_avg_500', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank_list_50', models.CharField(max_length=300)),
                ('expected_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Character')),
                ('game_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rank.GameUser')),
                ('team_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.TeamType')),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('from_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_from', to='rank.GameUser')),
                ('to_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_to', to='rank.GameUser')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
