# Generated by Django 3.0.7 on 2020-07-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('picture', models.URLField()),
                ('game_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.GameUser')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
