# Generated by Django 3.0.7 on 2020-07-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_difference', models.IntegerField()),
                ('is_retired', models.BooleanField(default=False)),
                ('track_name', models.CharField(max_length=100)),
                ('kart_name', models.CharField(max_length=50)),
                ('lap_time', models.CharField(max_length=50)),
                ('match_id_list', models.TextField()),
                ('game_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rank.GameUser')),
            ],
            options={
                'db_table': 'user_matches',
            },
        ),
    ]
